name: Build, Clean, and Push to Azure Container Registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-clean-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
    - name: Clean old images and containers
      env:
        IMAGE_NAME: marvin_dojo
      run: |
        # Remove all containers using the image
        docker ps -a | grep ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/$IMAGE_NAME | awk '{print $1}' | xargs -r docker rm -f
        
        # Remove all images with the same name
        docker images | grep ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/$IMAGE_NAME | awk '{print $3}' | xargs -r docker rmi -f
    
    - name: Build and push Docker image
      env:
        IMAGE_NAME: marvin_dojo
      run: |
        ls -R  # List directory contents for debugging
        docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/$IMAGE_NAME:latest -f ../Dockerfile ../
        docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/$IMAGE_NAME:latest